# On every push this script is executed
name: Build and deploy GH Pages
on: 
  push:
    branches:
      - zola
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/zola'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}