# On every push this script is executed
name: Build and deploy GH Pages
on: 
  push:
    branches:
      - zola
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/zola'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: build 
        run: |
          git clone --depth=1 -b xsro https://github.com/xsro/zola.git _zola
          cd _zola
          cargo run -- --root .. build
          cd ..
          cargo build --release
          cp _zola/target/release/zola public/zola
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/zola'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public